#!/usr/bin/env bash

WALLPAPERS="$XDG_PICTURES_DIR/wallpapers"
PATH_CACHE_FRAGMENT="$XDG_CONFIG_HOME/eww/paths"

echo > "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/alto"/* >> "$PATH_CACHE_FRAGMENT/$1" 
ls "$WALLPAPERS/anime"/* >> "$PATH_CACHE_FRAGMENT/$1" 
ls "$WALLPAPERS/dracula"/* >> "$PATH_CACHE_FRAGMENT/$1" 
ls "$WALLPAPERS/eyecandy"/* >> "$PATH_CACHE_FRAGMENT/$1" 
ls "$WALLPAPERS/mechanical"/* >> "$PATH_CACHE_FRAGMENT/$1" 
ls "$WALLPAPERS/minimal"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/monokai"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/nord"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/onedark"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/outrun"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/pixel"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/portrait"/* >> "$PATH_CACHE_FRAGMENT/$1"
ls "$WALLPAPERS/profiles"/* >> "$PATH_CACHE_FRAGMENT/$1"

